dist: bionic

services:
  - docker

before_install:
  - docker version
  - docker-compose version
  - docker build -t slurm-cluster-julia -f ci/Dockerfile .
  - docker-compose -f ci/docker-compose.yml up -d
  - docker ps

before_script:
  - docker exec -it slurmctld pwd
  - docker exec -it slurmctld ls -l
  - docker exec -it slurmctld srun -n 4 hostname

script:
  - docker exec -it slurmctld julia -e 'using Pkg; Pkg.build(verbose=true)'
  - docker exec -it slurmctld julia -e 'using Pkg; Pkg.test()'
